name: Sort imports

on:
  ["push"]

permissions:
  contents: write
  
jobs:
  sort:
    name: Sort imports
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps: 
        - uses: actions/checkout@v4
        - name: Setup python
          uses: actions/setup-python@v4
          with:
            python-version: 3.11
        
        - name: Install isort
          run: pip install isort --break-system-packages 
        
        - name: Sort imports
          run: python3 -m isort .
        
        - name: Check for changes and commit
          run: |
            git config --global user.name "Github Actions"
            git config --global user.email "username@users.noreply.github.com"
        
            git add -A

            
            latest_commit_message=$(git log -1 --pretty=%B)

            if ! git diff --cached --quiet; then
                git commit -a -m "Sorted import for commit: $latest_commit_message"
                git push
            fi
